### ISSUE TITLE
Some issues applying SplitGNN to my own data set

### ISSUE THREAD

**Issue by MarkeyGeng** [Split-GNN/SplitGNN#1]
Hello, if I want to apply splitgnn to my data set, do I have to convert it to dgl format as the picture？
![image](https://github.com/Split-GNN/SplitGNN/assets/50792384/a7511cd2-eeb6-4379-9e80-86d95b80c0ec)
I found that yelp and amazon data sets are also processed into similar structures

**Comment by blackboxo** [comment]
Yes. You need to transform your own data to DGL format. You can use the code in data_preprocess.py as a reference.

**Comment by MarkeyGeng** [comment]
Thanks for your answer! You can close the issue.
