### ISSUE TITLE
关于FDCompCN数据集的问题

### ISSUE THREAD

**Issue by judy-dong** [Split-GNN/SplitGNN#2]
您好我们想构建关于欺诈的数据集，但是不确定您的源数据是什么样的，因为您只上传了最终的图文件，可否提供源数据demo,让我们大概了解形式方便构建，谢谢

**Comment by judy-dong** [comment]
另外，我查看了您的.dgl文件，我发现可能是将不同年份的数据放在同一张图内，那计算2021年是否会发生舞弊时，会结合到邻居节点的信息，但是邻居节点存在未来数据，也就是用未来数据预测现在，会不会存在数据窥探呀，或者我的分析是错误的，因为没有get构建图的源文件

**Comment by blackboxo** [comment]
Thank you for your attention to our work. You can access CSMAR for the original data. The features are constructed based on the latest year's information of enterprises.

**Comment by judy-dong** [comment]
如果您的特征是基于最新一年的所构建的，那您的标签的年份是如何定义的呢，您是用什么年份范围的特征区域预测什么年份范围的欺诈标签呢~感谢您的回复

**Comment by blackboxo** [comment]
The labels are defined on violations disclosed by Chinese regulators in previous years.

**Comment by judy-dong** [comment]
您是用每一年的x计算每一年的y还是用前几年的x计算最后一年的y呢

**Comment by blackboxo** [comment]
We count the number of violations in the previous years to define the label of current year. The information of violations is not included in the features.
