### ISSUE TITLE
您好，这个新数据集跑起来有个错误

### ISSUE THREAD

**Issue by kaqiz** [Split-GNN/SplitGNN#4]
感谢您的工作，我想请问一下这个comp数据集解压后不是处理过的吗应该，但我运行的时候显示 `   self.input_dim = g.nodes['r'].data['feature'].shape[1]  # nodes['company'] for FDCompCN
  File "/home/anaconda3/lib/python3.10/site-packages/dgl/view.py", line 41, in __getitem__
    ntid = self._typeid_getter(ntype)
  File "/home/anaconda3/lib/python3.10/site-packages/dgl/heterograph.py", line 1332, in get_ntype_id
    raise DGLError('Node type "{}" does not exist.'.format(ntype))
dgl._ffi.base.DGLError: Node type "r" does not exist.`这是为什么呢？谢谢！我是直接运行的python train.py --dataset comp

**Comment by blackboxo** [comment]
the name for node is different for this dataset, as described in the code, use `g.nodes['company']` rather than `g.nodes['r']`

**Comment by kaqiz** [comment]
> the name for node is different for this dataset, as described in the code, use `g.nodes['company']` rather than `g.nodes['r']`

ok，thanks a lot，best wishes!
