### ISSUE TITLE
您好！请问能否给出处理第三个数据集的代码？感谢！

### ISSUE THREAD

**Issue by zx332211** [Split-GNN/SplitGNN#5]
您好！请问能否给出处理第三个数据集的代码？感谢！

**Comment by McfhHolmes0** [comment]
请问，可以上传FDCompCN数据集的处理代码

**Comment by blackboxo** [comment]
please send an email to bwu18@fudan.edu.cn. Thanks

**Comment by zx332211** [comment]
不需要了，谢谢你呀！




.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Split-GNN/SplitGNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月10日(星期三) 下午5:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Split-GNN/SplitGNN] 您好！请问能否给出处理第三个数据集的代码？感谢！ (Issue #5)





 
please send an email to ***@***.*** Thanks
